# required
version: 2

formats:
    - htmlzip

python:
    version: 3
    install:
        - method: pip
          path: .
    system_packages: true

conda:
    environment: environment.yml

build:
    image: latest

sphinx:
    builder: html
    configuration: docs/source/conf.py
