language: python
python:
  - "3.6"

branches:
  only:
   - master
   - stable

os:
  - windows
  - linux
  - osx

before_install:
  # install conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/.conda
  - export PATH="$HOME/.conda/bin:$PATH"
  - hash -r

  # disable interactions
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  
  - conda info -a

install:
  # create conda environment
  - conda create -q -n workspace python=$TRAVIS_PYTHON_VERSION numpy
  - conda activate workspace

  - python --version

  - pip install .

before_script:

script:
 - pytest

after_success:

before_deploy:

deploy:

after_script: