# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:
- job: 'linux'

  pool:
    vmImage: 'ubuntu-16.04'

  strategy:
    matrix:
      py36:
        python.version: '3.6'
      py37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(python.version)
    displayName: Use Python $(python.version)

  - script: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - script: conda create --yes --quiet --name workspace python=$(python.version) numpy scipy
    displayName: Create Anaconda environment

  - script: |
      source activate workspace
      python -m pip install --upgrade pip
      pip install .
    displayName: Install uToolbox package

  # TODO pytest

  - script: |
      pip install cibuildwheel
      cibuildwheel --output-dir wheelhouse .
    displayName: Build Python wheel

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'linux-nightly'
      publishLocation: 'Container'
