# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:
- job: 'linux'

  pool:
    vmImage: 'ubuntu-16.04'

  strategy:
    matrix:
      py36:
        python.version: '3.6'
      py37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: sudo install -d -m 0777 /usr/local/miniconda/envs
    displayName: 'Fix Anaconda permissions'

  - task: CondaEnvironment@0
    inputs:
      environmentName: 'workspace'
      packageSpecs: 'python=$(python.version) numpy scipy'
      createOptions: '--yes --quiet'
    displayName: 'Create Aanconda environment'

  - script: |
      conda activate workspace
      python -m pip install --upgrade pip
      pip install .
    displayName: 'Install uToolbox package'
