name: utoolbox

channels:
  - defaults
  - conda-forge

dependencies:
  # core
  - python=3
  - cython

  # numerics
  - numpy
  - pandas
  - scipy

  # file I/O
  - conda-forge::imageio

  # visualize
  - pyqt
  - pyopengl
  - conda-forge::vispy
  - matplotlib

  # utils
  - scikit-image
  - click
  - pip:
    - boltons
