name: utoolbox

channels:
  - defaults
  - conda-forge

dependencies:
  # core
  - python=3
  - cython

  # numerics
  - numpy
  - pandas

  # parallel
  - dask
  - distributed

  # file I/O
  - conda-forge::imageio

  # visualize
  - pyqt
  - pyopengl
  - conda-forge::vispy

  # utils
  - scikit-image
  - pip:
    - boltons
