name: utoolbox

channels:
  - defaults
  - conda-forge

dependencies:
  # core
  - python=3
  - ipykernel

  # numerics
  - numpy
  - pandas
  - scipy

  # file I/O
  - conda-forge::imageio

  # visualize
  - pyqt
  - pyopengl
  - conda-forge::vispy
  - matplotlib
  - progressbar2

  # distributed
  - dask
  - distributed

  # utils
  - ipywidgets
  - scikit-image
  - click
  - pip:
    - boltons
