name: utoolbox-dev

channels:
    - defaults
    - conda-forge

dependencies:
    # core
    - python=3

    # build tools
    - bumpversion
    - twine

    # linter
    - flake8
    # formatter
    - black
    
    # docs
    - sphinx
    - sphinx_rtd_theme

    # tests
    - pytest
    - coverage
    - pytest-cov

    # native libraries
    #  numpy from conda has mkl support
    - numpy
    #  av libraries is easier to install using conda
    - av