name: utoolbox

channels:
    - defaults
    - conda-forge

dependencies:
    # core
    - python=3.6
    - cython
    - ipykernel

    # numerics and processing
    - numpy
    - scipy

    # file I/O
    - imageio
    - tifffile

    # gui
    - pyqt

    # parallel
    - dask
    - pyopencl

    # utils
    - click
    - boltons
