name: utoolbox

channels:
  - conda-forge
  - simpleitk

dependencies:
  # core
  - python=3.6
  - cython
  - ipykernel
  - pyopencl

  # numerics and processing
  - numpy
  - pandas
  - scipy
  - scikit-image
  - simpleitk

  # file I/O
  - imageio

  # visual
  - progressbar2
  - pyqt
  - vispy
  - matplotlib

  # distributed
  - dask
  - distributed

  # utils
  - ipywidgets
  - click

  # pip
  - pip:
    - boltons
    #- pycuda
