name: utoolbox

channels:
  - defaults
  - conda-forge
  - simpleitk

dependencies:
  # core
  - python=3.6
  - cython
  - ipykernel
  - pyopencl

  # numerics and processing
  - numpy
  - pandas
  - scipy
  - scikit-image
  - simpleitk

  # file I/O
  - imageio
  - tifffile

  # visual
  - progressbar2
  - vispy
  - matplotlib
  # 2018.05.25
  # pyqt from conda-forge will source from outdated SIP causing segfault
  - pyqt

  # distributed
  - dask
  - distributed

  # utils
  - ipywidgets
  - click

  # pip
  - pip:
    - boltons
