name: utoolbox

channels:
  - defaults

dependencies:
  # core
  - python=3.6
  - cython
  - ipykernel
  
  # numerics
  - numpy
  - pandas
  - scipy

  # file I/O
  - imageio

  # visual
  - progressbar2
  - pyqt
  #- conda-forge::vispy
  - matplotlib

  # distributed
  - dask
  - distributed

  # utils
  - ipywidgets
  - scikit-image
  - click

  # pip
  - pip:
    - boltons
    - pycuda
