name: utoolbox

channels:
  - conda-forge
  - simpleitk

dependencies:
  # core
  - python=3.6
  - cython
  - ipykernel
  - pyopencl

  # numerics and processing
  - numpy
  - pandas
  - scipy
  - scikit-image
  - simpleitk

  # file I/O
  - imageio

  # visual
  - progressbar2
  - vispy
  - matplotlib

  # distributed
  - dask
  - distributed

  # utils
  - ipywidgets
  - click

  # pip
  - pip:
    - boltons
    # 2018.05.25
    # Install from conda will force install MKL instead of OpenBLAS
    - tifffile
    # 2018.05.25
    # pyqt from conda-forge will source from outdated SIP causing segfault
    - pyqt5
