name: utoolbox

channels:
  - defaults
  - conda-forge

dependencies:
  # core
  - python=3.6
  - cython
  - ipykernel

  # numerics and processing
  - numpy
  - xarray
  - pandas
  - scipy

  # file I/O
  - imageio
  - tifffile

  # visual
  - matplotlib
  # 2018.05.25
  # pyqt from conda-forge will source from outdated SIP causing segfault

  # parallel
  - dask
  - pyopencl

  # utils
  - click

  # pip
  - pip:
    - boltons
