name: utoolbox-dev

channels:
    - defaults
    - conda-forge

dependencies:
    # core
    - python=3

    # build tools
    - bumpversion
    - twine
    
    # docs
    - sphinx
    - sphinx_rtd_theme

    # tests
    - pytest
    - coverage
    - pytest-cov

    # numpy dependency
    # NOTE Pre-install numpy until upstream pycuda can incorporate
    # https://stackoverflow.com/q/27021270/ in its aksetup_helper.py
    - numpy

    # native libraries
